[package]
name = "zou"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.4", features = ["derive", "env"] }
dotenvy = { version = "0.15.7", features = ["clap"] }
home = "0.5.4"
names = { version = "0.14.0", default-features = false }
