[package]
name = "zou"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.4", features = ["derive"] }
flate2 = "1.0.25"
names = { version = "0.14.0", default-features = false }
tar = "0.4.38"
